### ISSUE TITLE
Home Page

### ISSUE THREAD

**Issue by AbinVarghexe** [iedcajce/IEDC-Website#1]
Look at this website :- https://www.boardofinnovation.com

Home page should match this website

We can we Components from :- https://magicui.design and https://ui.shadcn.com

check this word file more details :-

[IEDC Website.pdf](https://github.com/user-attachments/files/17530719/IEDC.Website.pdf)

HomePage Contents:-

Navbar
HeroSection
Dynamically changing event component

Assigned to :- @jaganrajcj

**Comment by AbinVarghexe** [comment]
> Look at this website :- https://www.boardofinnovation.com
> 
> Home page should match this website
> 
> We can we Components from :- https://magicui.design and https://ui.shadcn.com
> 
> check this word file more details :-
> 
> [IEDC Website.pdf](https://github.com/user-attachments/files/17530719/IEDC.Website.pdf)
> 
> HomePage Contents:-
> 
> Navbar HeroSection Dynamically changing event component
> 
> Assigned to :- @jaganrajcj

**Comment by AbinVarghexe** [comment]
> Look at this website :- https://www.boardofinnovation.com
> 
> Home page should match this website
> 
> We can we Components from :- https://magicui.design and https://ui.shadcn.com
> 
> check this word file more details :-
> 
> [IEDC Website.pdf](https://github.com/user-attachments/files/17530719/IEDC.Website.pdf)
> 
> HomePage Contents:-
> 
> Navbar HeroSection Dynamically changing event component
> 
> Assigned to :- @jaganrajcj
>
> **1.Thier is a minor bug in the mob view section that hamburger menu is not displayed and if their are more than 5 menu option add a load more button to display rest
>  2. Making the navbar fixed at the top would be better**

**Comment by jaganrajcj** [comment]
> > Look at this website :- https://www.boardofinnovation.com
> > Home page should match this website
> > We can we Components from :- https://magicui.design and https://ui.shadcn.com
> > check this word file more details :-
> > [IEDC Website.pdf](https://github.com/user-attachments/files/17530719/IEDC.Website.pdf)
> > HomePage Contents:-
> > Navbar HeroSection Dynamically changing event component
> > Assigned to :- @jaganrajcj
> > **1.Thier is a minor bug in the mob view section that hamburger menu is not displayed and if their are more than 5 menu option add a load more button to display rest
> > 2. Making the navbar fixed at the top would be better**

The lack of hamburger design is a known issue, It's not the final design and still has some refining and styling to do, so hamburger will be done as a part of that.

**Comment by AbinVarghexe** [comment]
Ok
