### ISSUE TITLE
About Us

### ISSUE THREAD

**Issue by AbinVarghexe** [iedcajce/IEDC-Website#3]
![Screenshot 2024-10-26 221630](https://github.com/user-attachments/assets/7b6895b4-0191-42af-a6ac-bb8a25c61adc)

From here to just before Our work can be completed

Look at this website :- https://www.boardofinnovation.com/

Home page should match this website

We can we Components from :- https://magicui.design/ and https://ui.shadcn.com/

check this word file more details :-

[IEDC Website.pdf](https://github.com/user-attachments/files/17530719/IEDC.Website.pdf)

Assigned tp :- @aibaljose

**Comment by aibaljose** [comment]
updated About-us setion

**Comment by AbinVarghexe** [comment]
Could you add the Sliding logo animation of the companies 

Do check out in the web site:-https://www.boardofinnovation.com

it is better to use magic Ui package for created in please check this out :-https://magicui.design/docs/components/scroll-based-velocity 
decrease the velocity value
 (only a suggestion)
