### ISSUE TITLE
Blog/News

### ISSUE THREAD

**Issue by AbinVarghexe** [iedcajce/IEDC-Website#8]
![Screenshot 2024-10-26 224745](https://github.com/user-attachments/assets/646c728d-d37f-4560-86b3-88065804f3ba)
Look at this website :- https://www.boardofinnovation.com/

Home page should match this website

We can we Components from :- https://magicui.design/ and https://ui.shadcn.com/

check this word file more details :-

[IEDC Website.pdf](https://github.com/user-attachments/files/17530719/IEDC.Website.pdf)

Assigned to :- @aibaljose 

Add this section a as report section with a button to redirect to report page and now add a Lorem title and a button

AND ALSO complete **Footer Section**

**Comment by aibaljose** [comment]
can you give more details about this task

**Comment by AbinVarghexe** [comment]
Updated just check

**Comment by AbinVarghexe** [comment]
updated what to add check those

**Comment by aibaljose** [comment]
blog added
